Repository WildCodeSchool/orleans-0918-php-matchmaking, pull requests merged in 2018-11, with the labels that each got.

#24 fix template
  .gitignore
  .travis.yml
  composer.json
  composer.lock
  phpcs.xml.dist
  symfony.lock
  templates/base.html.twig
  webpack.config.js
Labels: Corrections done, Reviewed by PO

#35 Fix master
  assets/js/app.js
  composer.lock
  config/packages/twig.yaml
  templates/base.html.twig
Labels: Reviewed by PO

#34 Us 56
  assets/css/app.scss
  assets/fonts/BrandonText-Bold.otf
  assets/js/app.js
  package.json
  templates/base.html.twig
  templates/navbar.html.twig
  yarn.lock
Labels: Reviewed by PO

#52 Dev to Master
  assets/css/app.scss
  assets/fonts/BrandonText-Bold.otf
  assets/js/app.js
  composer.lock
  config/packages/twig.yaml
  package.json
  templates/base.html.twig
  templates/navbar.html.twig
  yarn.lock
Labels: Reviewed by PO

#54 Us22 add event
  src/Controller/EventController.php
  src/Entity/Event.php
  src/Form/EventType.php
  src/Migrations/Version20181121125420.php
  src/Migrations/Version20181121141538.php
  src/Migrations/Version20181121151849.php
  src/Migrations/Version20181122120026.php
  src/Repository/EventRepository.php
  src/Validator/Constraints/IsFutureDate.php
  src/Validator/Constraints/IsFutureDateValidator.php
  templates/event/add.html.twig
Labels: Reviewed by PO

#55 S2 us50 ajout utilisateur
  assets/css/app.scss
  config/packages/security.yaml
  src/Controller/SecurityController.php
  src/Controller/UserController.php
  src/Entity/User.php
  src/Form/User1Type.php
  src/Form/UserType.php
  src/Migrations/Version20181128085942.php
  src/Migrations/Version20181128091642.php
  src/Migrations/Version20181128092519.php
  src/Repository/UserRepository.php
  src/Security/AppAuthenticator.php
  templates/user/_delete_form.html.twig
  templates/user/_form.html.twig
  templates/user/edit.html.twig
  templates/user/index.html.twig
  templates/user/login.html.twig
  templates/user/new.html.twig
  templates/user/new_manager.html.twig
  templates/user/show.html.twig
Labels: Corrections done, Reviewed by PO

#56 Us10 gestion timer
  src/Controller/SettingsController.php
  src/Entity/Timer.php
  src/Form/TimerType.php
  src/Migrations/Version20181128102146.php
  src/Repository/TimerRepository.php
  templates/settings/_formTimer.html.twig
  templates/settings/index.html.twig
Labels: Reviewed by PO

#60 Dev
  assets/css/app.scss
  config/packages/security.yaml
  src/Controller/EventController.php
  src/Controller/SecurityController.php
  src/Controller/SettingsController.php
  src/Controller/UserController.php
  src/Entity/Event.php
  src/Entity/Timer.php
  src/Entity/User.php
  src/Form/EventType.php
  src/Form/TimerType.php
  src/Form/User1Type.php
  src/Form/UserType.php
  src/Migrations/Version20181128102146.php
  src/Migrations/Version20181129094058.php
  src/Repository/EventRepository.php
  src/Repository/TimerRepository.php
  src/Repository/UserRepository.php
  src/Security/AppAuthenticator.php
  src/Validator/Constraints/IsFutureDate.php
  src/Validator/Constraints/IsFutureDateValidator.php
  templates/event/add.html.twig
  templates/settings/_formTimer.html.twig
  templates/settings/index.html.twig
  templates/user/_delete_form.html.twig
  templates/user/_form.html.twig
  templates/user/edit.html.twig
  templates/user/index.html.twig
  templates/user/login.html.twig
  templates/user/new.html.twig
  templates/user/new_manager.html.twig
  templates/user/show.html.twig
Labels: Reviewed by PO

#57 Sprint 02 us11 liste formats evenements
  assets/css/app.scss
  src/Controller/SettingsController.php
  src/Entity/FormatEvent.php
  src/Migrations/Version20181128160021.php
  src/Repository/FormatEventRepository.php
  templates/_navbar.html.twig
  templates/base.html.twig
  templates/settings/_listFormatEvent.html.twig
  templates/settings/index.html.twig
Labels: Conflits done, Reviewed by PO

#62 Fix add event timers
  src/Controller/EventController.php
  src/Entity/Event.php
  src/Form/EventType.php
  src/Migrations/Version20181129171348.php
Labels: Reviewed by PO

#63 Us 24 edit event
  src/Controller/EventController.php
  templates/event/edit.html.twig
Labels: Reviewed by PO

#65 fix #codesniffer
  src/Security/AppAuthenticator.php
Labels: Reviewed by PO

#66 travis upgrade version
  .travis.yml
Labels: Reviewed by PO

#61 Us 20 list events
  assets/css/event_list.scss
  assets/js/app.js
  src/Controller/EventController.php
  templates/base.html.twig
  templates/event/list.html.twig
Labels: Corrections done, Reviewed by PO

#67 fix use manquant
  src/Controller/EventController.php
Labels: Reviewed by PO

#68 Dev to Master
  .travis.yml
  assets/css/app.scss
  assets/css/event_list.scss
  assets/js/app.js
  src/Controller/EventController.php
  src/Controller/SettingsController.php
  src/Entity/Event.php
  src/Entity/FormatEvent.php
  src/Form/EventType.php
  src/Migrations/Version20181128160021.php
  src/Migrations/Version20181129171348.php
  src/Repository/FormatEventRepository.php
  src/Security/AppAuthenticator.php
  templates/_navbar.html.twig
  templates/base.html.twig
  templates/event/edit.html.twig
  templates/event/list.html.twig
  templates/settings/_listFormatEvent.html.twig
  templates/settings/index.html.twig
Labels: Reviewed by PO
