Repository WildCodeSchool/orleans-0918-php-matchmaking, pull requests merged in 2018-12, with the labels that each got.

#69 Us 28 delete event
  assets/css/event_list.scss
  src/Controller/EventController.php
  templates/event/index.html.twig
Labels: Corrections done, Reviewed by PO

#83 FIX_82_UNIFORMISATION_FLASH_MESSAGE
  src/Controller/EventController.php
  src/Controller/SettingsController.php
  templates/base.html.twig
Labels: Reviewed by PO

#85 Dev to master
  assets/css/event_list.scss
  src/Controller/EventController.php
  src/Controller/SettingsController.php
  src/Entity/Event.php
  src/Entity/FormatEvent.php
  src/Form/EventType.php
  src/Migrations/Version20181203143058.php
  templates/_navbar.html.twig
  templates/base.html.twig
  templates/event/add.html.twig
  templates/event/index.html.twig
Labels: Reviewed by PO

#64 S2 us53 liste des utilisateurs
  assets/css/app.scss
  assets/js/app.js
  assets/js/updateForm.js
  src/Controller/UserController.php
  templates/user/_form.html.twig
  templates/user/_list.html.twig
  templates/user/index.html.twig
  templates/user/manager.html.twig
  templates/user/new_manager.html.twig
Labels: Corrections done, Reviewed by PO

#86 FIX_84_AJOUT_FIXTURES
  composer.json
  composer.lock
  config/bundles.php
  src/DataFixtures/EventFixtures.php
  src/DataFixtures/FormatEventFixtures.php
  src/DataFixtures/TimerFixtures.php
  src/DataFixtures/UserFixtures.php
  symfony.lock
Labels: Reviewed by PO

#87 Sprint 03 us25b choix format evenement form edition
  templates/event/edit.html.twig
Labels: Reviewed by PO

#91 S3 us54 suppression utilisateurs
  assets/css/app.scss
  src/Controller/UserController.php
  templates/user/_delete_form.html.twig
  templates/user/_list.html.twig
Labels: Corrections done, Reviewed by PO

#89 Us23 Ajout du logo lors de l'ajout evenement
  .gitignore
  assets/css/app.scss
  assets/js/app.js
  composer.json
  composer.lock
  config/bundles.php
  config/packages/vich_uploader.yaml
  public/images/logos/defaultLogo.png
  src/Controller/EventController.php
  src/Entity/Event.php
  src/Form/EventType.php
  src/Migrations/Version20181204160856.php
  symfony.lock
  templates/event/add.html.twig
  templates/event/edit.html.twig
Labels: Corrections done, Reviewed by PO

#96 fix_95_dev
  assets/css/app.scss
  src/DataFixtures/EventFixtures.php
  src/Security/AppAuthenticator.php
  templates/_navbar.html.twig
  templates/user/_form.html.twig
  templates/user/manager.html.twig
Labels: Reviewed by PO

#94 Us21 pagination
  composer.json
  composer.lock
  config/bundles.php
  config/packages/framework.yaml
  config/packages/knp_paginator.yaml
  config/services.yaml
  src/Controller/EventController.php
  symfony.lock
  templates/event/index.html.twig
  translations/KnpPaginatorBundle.fr.yml
Labels: Reviewed by PO

#99 Fix event delete button
  .env
  assets/css/event_list.scss
  public/.htaccess
  templates/event/index.html.twig
Labels: Reviewed by PO

#100 fix upload, order by asc in managerList
  config/packages/vich_uploader.yaml
  src/Controller/UserController.php
  templates/user/_list.html.twig
Labels: Reviewed by PO

#105 fix upload logo
  config/packages/vich_uploader.yaml
Labels: Reviewed by PO

#104 FIX_103_FORMATEVENT_RENDER_VUE
  src/Controller/SettingsController.php
Labels: Reviewed by PO

#106 Sprint 04 us22b us25b statut evenement
  .gitignore
  _composer.lock
  composer.json
  composer.lock
  src/Controller/EventController.php
  src/DataFixtures/EventFixtures.php
  src/DataFixtures/StatusEventFixtures.php
  src/Entity/Event.php
  src/Entity/StatusEvent.php
  src/Form/EventType.php
  src/Migrations/Version20181211135118.php
  src/Repository/StatusEventRepository.php
  symfony.lock
  templates/event/edit.html.twig
  templates/event/index.html.twig
Labels: Reviewed by PO

#111 Dev
  src/Controller/EventController.php
  src/Controller/SettingsController.php
  src/DataFixtures/AppFixtures.php
  src/DataFixtures/EventFixtures.php
  src/DataFixtures/StatusEventFixtures.php
  src/Entity/Event.php
  src/Entity/FormatEvent.php
  src/Entity/StatusEvent.php
  src/Form/EventType.php
  src/Migrations/Version20181211135118.php
  src/Repository/StatusEventRepository.php
  templates/event/edit.html.twig
  templates/event/index.html.twig
  templates/settings/_listFormatEvent.html.twig
Labels: Reviewed by PO

#108 Us27 event manager
  assets/css/event_manager.scss
  assets/js/app.js
  src/Entity/Event.php
  src/Entity/User.php
  src/Form/EventType.php
  src/Migrations/Version20181213134246.php
  templates/event/add.html.twig
  templates/event/edit.html.twig
Labels: Corrections done, Reviewed by PO

#93 S3 us55 edition utilisateurs
  assets/css/app.scss
  assets/js/updateForm.js
  phpunit.xml.dist
  src/Controller/UserController.php
  templates/user/_form.html.twig
  templates/user/_list.html.twig
Labels: Conflits done

#113 Dev to Master
  assets/css/app.scss
  assets/css/event_manager.scss
  assets/js/app.js
  assets/js/updateForm.js
  phpunit.xml.dist
  src/Controller/UserController.php
  src/Entity/Event.php
  src/Entity/User.php
  src/Form/EventType.php
  src/Migrations/Version20181213134246.php
  templates/event/add.html.twig
  templates/event/edit.html.twig
  templates/user/_form.html.twig
  templates/user/_list.html.twig
Labels: Reviewed by PO

#97 Us31 ajout de participant
  src/Controller/PlayerController.php
  src/Entity/Event.php
  src/Entity/Player.php
  src/Form/PlayerType.php
  src/Migrations/Version20181205165644.php
  src/Migrations/Version20181211133836.php
  src/Repository/PlayerRepository.php
  templates/player/_formPlayer.html.twig
  templates/player/index.html.twig
Labels: Corrections done, Reviewed by PO

#115 Dev to Master
  src/Controller/PlayerController.php
  src/Entity/Event.php
  src/Entity/Player.php
  src/Form/PlayerType.php
  src/Migrations/Version20181205165644.php
  src/Migrations/Version20181211133836.php
  src/Repository/PlayerRepository.php
  templates/player/_formPlayer.html.twig
  templates/player/index.html.twig
Labels: Reviewed by PO

#114 Us40 affichage titre logo
  assets/css/dashboard.scss
  assets/js/dashboard.js
  src/Controller/DashboardController.php
  src/Migrations/Version20181211085539.php
  templates/dashboard/pause.html.twig
  templates/dashboard/run.html.twig
  templates/dashboardBase.html.twig
  webpack.config.js
Labels: Corrections done, Reviewed by PO

#117 Fix uniformisation boutons
  .gitignore
  assets/css/app.scss
  symfony.lock
  templates/user/_delete_form.html.twig
  templates/user/_list.html.twig
Labels: Reviewed by PO

#123 Sprint 05 us06 generation password aleatoire
  src/Controller/UserController.php
  src/Service/PasswordGenerator.php
Labels: Reviewed by PO

#130 FIX_128_DEV_SCSS_VARIABLES
  assets/css/app.scss
  assets/css/dashboard.scss
  assets/css/event_list.scss
Labels: Reviewed by PO

#112 S4 US63 Liste admins
  src/Controller/UserController.php
  src/Repository/UserRepository.php
  templates/user/_list.html.twig
  templates/user/admin.html.twig
  templates/user/manager.html.twig
Labels: Conflits done, Reviewed by PO

#132 Dev to Master
  assets/css/app.scss
  assets/css/dashboard.scss
  assets/css/event_list.scss
  src/Controller/UserController.php
  src/Repository/UserRepository.php
  src/Service/PasswordGenerator.php
  templates/user/_list.html.twig
  templates/user/admin.html.twig
  templates/user/manager.html.twig
Labels: Reviewed by PO

#135 S5 us60 Création admins
  assets/js/updateForm.js
  src/Controller/UserController.php
Labels: Reviewed by PO

#136 S5 us62 Edit admins
  assets/js/updateForm.js
Labels: Reviewed by PO

#134 S5_US61 Suppression admins
  src/Controller/UserController.php
Labels: Reviewed by PO

#133 S5 US34 suppression des participants
  src/Controller/PlayerController.php
  templates/player/index.html.twig
Labels: Reviewed by PO

#137 Dev to Master
  assets/js/updateForm.js
  src/Controller/PlayerController.php
  src/Controller/UserController.php
  templates/player/index.html.twig
Labels: Reviewed by PO

#131 Sprint 05 us07 envoi email avec identifiants
  composer.json
  composer.lock
  config/services.yaml
  src/Controller/UserController.php
  templates/emails/registration.html.twig
Labels: Corrections done, Reviewed by PO

#138 Dev to Master
  composer.json
  composer.lock
  config/services.yaml
  src/Controller/UserController.php
  templates/emails/registration.html.twig
Labels: Reviewed by PO
