Repository WildCodeSchool/orleans-0918-php-matchmaking, pull requests merged in 2019-01, with the labels that each got.

#142 FIX 140 STATUT EVENEMENT + COMPLEMENT GESTION STATUT
  src/Controller/EventController.php
  src/Controller/PlayerController.php
  src/Entity/StatusEvent.php
  src/Form/EventType.php
  templates/event/edit.html.twig
  templates/event/index.html.twig
  templates/player/index.html.twig
Labels: Reviewed by PO

#144 Us46 affichage tour table
  src/Controller/DashboardController.php
  templates/dashboard/pause.html.twig
  templates/dashboard/run.html.twig
Labels: Corrections done, Reviewed by PO

#147 relation society event
  src/DataFixtures/EventFixtures.php
  src/DataFixtures/SocietyFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Event.php
  src/Entity/Society.php
  src/Entity/User.php
  src/Form/EventType.php
  src/Migrations/Version20190103134141.php
  templates/event/add.html.twig
  templates/event/edit.html.twig
Labels: Reviewed by PO

#149 Dev to Master
  assets/js/app.js
  assets/js/presence.js
  package.json
  src/Controller/PlayerController.php
  src/DataFixtures/EventFixtures.php
  src/DataFixtures/SocietyFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Event.php
  src/Entity/Player.php
  src/Entity/Society.php
  src/Entity/User.php
  src/Form/EventType.php
  src/Migrations/Version20190103091852.php
  src/Migrations/Version20190103133639.php
  src/Migrations/Version20190103134141.php
  templates/event/add.html.twig
  templates/event/edit.html.twig
  templates/player/index.html.twig
  yarn.lock
Labels: Reviewed by PO

#148 Us43 affichage timer round
  assets/js/dashboard_run.js
  src/Controller/DashboardController.php
  templates/dashboard/run.html.twig
  webpack.config.js
Labels: Reviewed by PO

#152 Dev to Master
  assets/js/dashboard_run.js
  src/Controller/DashboardController.php
  templates/dashboard/run.html.twig
  webpack.config.js
Labels: Reviewed by PO

#150 SPRINT_06_US35_LANCEMENT_EVENEMENT
  assets/js/players.js
  src/Controller/EventController.php
  src/Entity/Player.php
  src/Migrations/Version20190103203551.php
  src/Migrations/Version20190103203805.php
  src/Repository/EventRepository.php
  templates/player/_modalStartGame.html.twig
  templates/player/index.html.twig
  webpack.config.js
Labels: Conflits done

#156 FIX_155_DEV_MIGRATIONS
  src/Migrations/Version20181128102146.php
  src/Migrations/Version20181128160021.php
  src/Migrations/Version20181129085426.php
  src/Migrations/Version20181129094058.php
  src/Migrations/Version20181129171348.php
  src/Migrations/Version20181203143058.php
  src/Migrations/Version20181204160856.php
  src/Migrations/Version20181205165644.php
  src/Migrations/Version20181211085539.php
  src/Migrations/Version20181211133836.php
  src/Migrations/Version20181211135118.php
  src/Migrations/Version20181213134246.php
  src/Migrations/Version20181226152233.php
  src/Migrations/Version20190103091852.php
  src/Migrations/Version20190103133639.php
  src/Migrations/Version20190103203551.php
  src/Migrations/Version20190103203805.php
  src/Migrations/Version20190104104403.php
Labels: Reviewed by PO

#157 Dev to Master
  src/Migrations/Version20181128102146.php
  src/Migrations/Version20181128160021.php
  src/Migrations/Version20181129085426.php
  src/Migrations/Version20181129094058.php
  src/Migrations/Version20181129171348.php
  src/Migrations/Version20181203143058.php
  src/Migrations/Version20181204160856.php
  src/Migrations/Version20181205165644.php
  src/Migrations/Version20181211085539.php
  src/Migrations/Version20181211133836.php
  src/Migrations/Version20181211135118.php
  src/Migrations/Version20181213134246.php
  src/Migrations/Version20181226152233.php
  src/Migrations/Version20190103091852.php
  src/Migrations/Version20190103133639.php
  src/Migrations/Version20190103203551.php
  src/Migrations/Version20190103203805.php
  src/Migrations/Version20190104104403.php
Labels: Reviewed by PO

#154 Us5 securisation des pages
  config/packages/security.yaml
  src/Controller/SecurityController.php
  templates/_navbar.html.twig
  templates/event/add.html.twig
  templates/event/edit.html.twig
  templates/event/index.html.twig
Labels: Reviewed by PO

#158 Us41 timer prise parole
  assets/css/dashboard.scss
  assets/js/dashboard_run.js
  package.json
  src/Controller/DashboardController.php
  templates/dashboard/run.html.twig
  yarn.lock
Labels: Reviewed by PO

#159 Us45 page preparation
  assets/css/dashboard.scss
  assets/js/dashboard.js
  src/Controller/DashboardController.php
  src/Controller/EventController.php
  templates/dashboard/start.html.twig
Labels: Reviewed by PO

#160 Dev to Master
  assets/css/dashboard.scss
  assets/js/dashboard.js
  assets/js/dashboard_run.js
  config/packages/security.yaml
  package.json
  src/Controller/DashboardController.php
  src/Controller/EventController.php
  src/Controller/SecurityController.php
  templates/_navbar.html.twig
  templates/dashboard/run.html.twig
  templates/dashboard/start.html.twig
  templates/event/add.html.twig
  templates/event/edit.html.twig
  templates/event/index.html.twig
  yarn.lock
Labels: Reviewed by PO

#161 page dashboard fin
  assets/css/dashboard.scss
  assets/js/dashboard_run.js
  src/Controller/DashboardController.php
  templates/dashboard/end.html.twig
Labels: Conflits done, Reviewed by PO

#166 Fix lancement
  templates/player/_modalStartGame.html.twig
Labels: Reviewed by PO

#162 SPRINT_06_US44_AFFICHAGE_DES_TABLES
  assets/css/dashboard.scss
  assets/js/dashboard.js
  src/Controller/DashboardController.php
  templates/dashboard/_viewTables.html.twig
  templates/dashboard/pause.html.twig
  templates/dashboard/start.html.twig
Labels: Reviewed by PO

#165 Us5 b affichage en fonction du role
  src/Controller/EventController.php
  src/Controller/UserController.php
  templates/_navbar.html.twig
  templates/event/edit.html.twig
  templates/user/_form.html.twig
  templates/user/_list.html.twig
Labels: Changes requested, question

#169 fix scss
  assets/css/dashboard.scss
Labels: Reviewed by PO

#168 FIX_167_CSS_+_W3C_PAGE_PARAMETRES
  assets/css/app.scss
  assets/fonts/BrandonText-Regular.otf
  assets/pictures/60-lines.png
  templates/_navbar.html.twig
  templates/base.html.twig
  templates/settings/_addFormatEvent_form.html.twig
  templates/settings/_formTimer.html.twig
  templates/settings/_listFormatEvent.html.twig
  templates/settings/index.html.twig
Labels: Conflits done

#173 Dev to master
  assets/css/app.scss
  assets/css/dashboard.scss
  assets/css/event_players.scss
  assets/fonts/BrandonText-Regular.otf
  assets/js/app.js
  assets/js/dashboard.js
  assets/js/dashboard_run.js
  assets/js/editPlayer.js
  assets/pictures/60-lines.png
  src/Controller/DashboardController.php
  src/Controller/EventController.php
  src/Controller/PlayerController.php
  src/Controller/UserController.php
  templates/_navbar.html.twig
  templates/base.html.twig
  templates/dashboard/_viewTables.html.twig
  templates/dashboard/end.html.twig
  templates/dashboard/pause.html.twig
  templates/dashboard/start.html.twig
  templates/event/edit.html.twig
  templates/player/_formPlayer.html.twig
  templates/player/_modalStartGame.html.twig
  templates/player/index.html.twig
  templates/settings/_addFormatEvent_form.html.twig
  templates/settings/_formTimer.html.twig
  templates/settings/_listFormatEvent.html.twig
  templates/settings/index.html.twig
  templates/user/_form.html.twig
  templates/user/_list.html.twig
Labels: Reviewed by PO

#175 FIX_174_CSS_W3C_PAGE_LOGIN
  assets/css/app.scss
  templates/_navbar.html.twig
  templates/base.html.twig
  templates/security/login.html.twig
Labels: Reviewed by PO

#177 Fix player phone
  src/Entity/Player.php
Labels: Reviewed by PO

#178 Fix timer speaker
  assets/css/dashboard.scss
  assets/js/dashboard_run.js
Labels: Reviewed by PO

#179 Fix status event end
  src/Controller/DashboardController.php
Labels: Reviewed by PO

#181 affichage nombre de participants
  templates/event/index.html.twig
Labels: Reviewed by PO

#182 S7 US27E Liste participants par société
  src/Controller/UserController.php
  templates/society/index.html.twig
  templates/user/manager.html.twig
Labels: Reviewed by PO

#185 FIX_184_MESSAGE_ERREURS_TWIG_PAGE_PARAMETRES
  templates/settings/_formTimer.html.twig
Labels: Reviewed by PO

#183 FIX_176_CSS_W3C_PAGE_EVENEMENT
  assets/css/event_list.scss
  templates/event/add.html.twig
  templates/event/edit.html.twig
  templates/event/index.html.twig
Labels: Conflits done, Reviewed by PO

#171 FIX_170_AJOUT_FORMATEVENT
  src/Controller/SettingsController.php
  src/Service/CsvFormatEvent.php
Labels: Corrections done, Reviewed by PO

#188 fix phone number
  src/Form/PlayerType.php
Labels: Reviewed by PO

#191 fix regex
  src/Entity/Player.php
Labels: Reviewed by PO

#202 add dashboard sounds
  assets/js/dashboard_pause.js
  assets/js/dashboard_run.js
  public/sounds/bip.wav
  public/sounds/gong.mp3
  public/sounds/speak.wav
  templates/dashboard/pause.html.twig
  templates/dashboard/run.html.twig
Labels: Reviewed by PO

#197 FIX_196_RETRAIT_CHECKMX
  src/Entity/User.php
Labels: Reviewed by PO

#200 fix redirection et affichage fin evenement
  templates/dashboard/end.html.twig
Labels: Reviewed by PO

#201 fix managers list
  src/Controller/UserController.php
  src/Repository/UserRepository.php
Labels: Reviewed by PO

#195 FIX_194_AFFICHAGE_LISTE_PERSONNES
  src/Entity/Event.php
  src/Entity/Society.php
  templates/player/index.html.twig
  templates/user/edit.html.twig
  templates/user/new.html.twig
  templates/user/show.html.twig
Labels: Conflits done, Reviewed by PO

#203 fix start link route
  templates/dashboard/start.html.twig
Labels: Reviewed by PO

#207 fix preselection society
  assets/js/updateForm.js
  templates/user/_list.html.twig
Labels: Reviewed by PO

#205 add parent() in twig script block (event add & edit)
  templates/event/_previewUpload.html.twig
  templates/event/add.html.twig
  templates/event/edit.html.twig
Labels: Reviewed by PO

#206 fix bug route
  src/Controller/UserController.php
Labels: Reviewed by PO

#209 FIX_204_AFFICHAGE_TIMER_LANCEMENT_EVENT
  templates/player/_modalStartGame.html.twig
Labels: Reviewed by PO

#210 Dev to master
  assets/css/event_players.scss
  assets/css/previewUpload.scss
  assets/js/dashboard_pause.js
  assets/js/dashboard_run.js
  assets/js/previewUpload.js
  assets/js/updateForm.js
  public/favicon.ico
  public/sounds/bip.wav
  public/sounds/gong.mp3
  public/sounds/speak.wav
  src/Controller/EventController.php
  src/Controller/UserController.php
  src/Entity/Event.php
  src/Entity/Player.php
  src/Entity/Society.php
  src/Entity/User.php
  src/Form/PlayerType.php
  src/Repository/UserRepository.php
  templates/base.html.twig
  templates/dashboard/end.html.twig
  templates/dashboard/pause.html.twig
  templates/dashboard/run.html.twig
  templates/dashboard/start.html.twig
  templates/event/_previewUpload.html.twig
  templates/event/add.html.twig
  templates/event/edit.html.twig
  templates/player/_formEditPlayer.html.twig
  templates/player/_formPlayer.html.twig
  templates/player/_modalStartGame.html.twig
  templates/player/index.html.twig
  templates/society/index.html.twig
  templates/user/_form.html.twig
  templates/user/_list.html.twig
  templates/user/admin.html.twig
  templates/user/edit.html.twig
  templates/user/manager.html.twig
  templates/user/new.html.twig
  templates/user/show.html.twig
  webpack.config.js
Labels: Reviewed by PO

#211 fix_legend
  assets/js/updateForm.js
  templates/user/_form.html.twig
Labels: Reviewed by PO

#212 Fix error message login
  src/Security/AppAuthenticator.php
Labels: Reviewed by PO

#213 FIX_198_CSS_GLOBAL_DASHBOARD
  assets/css/app.scss
  assets/css/dashboard.scss
  assets/js/dashboard.js
  assets/js/dashboard_run.js
  templates/dashboard/_viewTables.html.twig
  templates/dashboard/end.html.twig
  templates/dashboard/pause.html.twig
  templates/dashboard/run.html.twig
  templates/dashboard/start.html.twig
  templates/dashboardBase.html.twig
Labels: Reviewed by PO

#214 fix du décalage de la page
  assets/css/app.scss
  templates/user/manager.html.twig
Labels: Reviewed by PO

#215 tri dans la liste des evenements
  src/Controller/EventController.php
  templates/event/_event.html.twig
  templates/event/index.html.twig
Labels: Reviewed by PO

#216 Fix security paths
  src/Controller/DashboardController.php
  src/Controller/EventController.php
Labels: Reviewed by PO

#217 suppression email obligatoire des players
  src/Entity/Player.php
  src/Form/PlayerType.php
  src/Migrations/Version20190110103555.php
Labels: Reviewed by PO

#218 sécurité sur le lancement d'évènement
  src/Controller/EventController.php
Labels: Reviewed by PO

#219 fix liste evenements des 7 prochains jours
  templates/event/index.html.twig
Labels: Reviewed by PO

#221 evenements 7 prochains jours affichés par ordre chrono
  src/Controller/EventController.php
Labels: Reviewed by PO

#222 fix dashboard css
  assets/css/dashboard.scss
  templates/dashboard/end.html.twig
  templates/dashboard/run.html.twig
Labels: Reviewed by PO

#223 Dev to master
  assets/css/app.scss
  assets/css/dashboard.scss
  assets/js/dashboard.js
  assets/js/dashboard_run.js
  assets/js/updateForm.js
  src/Controller/DashboardController.php
  src/Controller/EventController.php
  src/Entity/Player.php
  src/Form/PlayerType.php
  src/Migrations/Version20190110103555.php
  src/Security/AppAuthenticator.php
  templates/_navbar.html.twig
  templates/dashboard/_viewTables.html.twig
  templates/dashboard/end.html.twig
  templates/dashboard/pause.html.twig
  templates/dashboard/run.html.twig
  templates/dashboard/start.html.twig
  templates/dashboardBase.html.twig
  templates/event/_event.html.twig
  templates/event/index.html.twig
  templates/user/_form.html.twig
  templates/user/manager.html.twig
Labels: Reviewed by PO

#225 Fix redirect
  src/Controller/EventController.php
Labels: Reviewed by PO

#226 Fix W3C
  src/Form/PlayerType.php
  templates/player/_formEditPlayer.html.twig
  templates/society/edit.html.twig
  templates/society/index.html.twig
  templates/society/new.html.twig
  templates/society/show.html.twig
Labels: Reviewed by PO

#224 Fix dashboard end css
  assets/css/dashboard.scss
Labels: Reviewed by PO

#227 Dev to master
  assets/css/dashboard.scss
  src/Controller/EventController.php
  src/Form/PlayerType.php
  templates/player/_formEditPlayer.html.twig
  templates/society/edit.html.twig
  templates/society/index.html.twig
  templates/society/new.html.twig
  templates/society/show.html.twig
Labels: Reviewed by PO

#228 fix titre depuis la page société
  templates/user/manager.html.twig
Labels: Reviewed by PO

#229 fix sounds dashboard
  assets/js/dashboard_end.js
  public/sounds/gong.mp3
  public/sounds/gong.wav
  templates/dashboard/end.html.twig
  templates/dashboard/pause.html.twig
  webpack.config.js
Labels: Reviewed by PO

#231 FIX_230_CHAMP_DESCRIPTION_EVENEMENT
  src/Entity/Event.php
  src/Form/EventType.php
  src/Migrations/Version20190114085547.php
Labels: Reviewed by PO

#233 fix users autho
  src/Controller/DashboardController.php
  src/Controller/EventController.php
  src/Controller/PlayerController.php
Labels: Reviewed by PO

#234 FIX_232_AJOUT_ICONE_LISTE_UTILISATEURS
  templates/user/_list.html.twig
Labels: Reviewed by PO

#236 fix society add user
  assets/js/updateForm.js
Labels: Reviewed by PO

#235 Fix required fields
  assets/css/app.scss
  templates/event/add.html.twig
  templates/event/edit.html.twig
  templates/player/_formEditPlayer.html.twig
  templates/player/_formPlayer.html.twig
  templates/society/_form.html.twig
  templates/user/_form.html.twig
Labels: Conflits done, Reviewed by PO

#240 Dev to Master
  assets/css/app.scss
  assets/js/dashboard_end.js
  assets/js/editPlayer.js
  assets/js/updateForm.js
  public/sounds/gong.mp3
  public/sounds/gong.wav
  src/Controller/DashboardController.php
  src/Controller/EventController.php
  src/Controller/PlayerController.php
  src/Controller/UserController.php
  src/Entity/Event.php
  src/Form/EventType.php
  src/Migrations/Version20190114085547.php
  templates/dashboard/end.html.twig
  templates/dashboard/pause.html.twig
  templates/event/add.html.twig
  templates/event/edit.html.twig
  templates/player/_formEditPlayer.html.twig
  templates/player/_formPlayer.html.twig
  templates/society/_form.html.twig
  templates/user/_form.html.twig
  templates/user/_list.html.twig
  templates/user/manager.html.twig
  webpack.config.js
Labels: Reviewed by PO

#242 FIX_UPDATE_UTILISATEURS
  assets/js/updateForm.js
  templates/user/_list.html.twig
Labels: Reviewed by PO

#243 Dev to Master
  assets/js/updateForm.js
  src/Controller/SocietyController.php
  src/Controller/UserController.php
  templates/user/_list.html.twig
Labels: Reviewed by PO

#246 FIX_245_MODAL_LANCEMENT_MESSAGE_ALERTE
  assets/js/players.js
  templates/player/_modalStartGame.html.twig
Labels: Reviewed by PO

#244 Readme
  README.md
Labels: Reviewed by PO

#247 Dev to Master
  README.md
  assets/js/players.js
  templates/player/_modalStartGame.html.twig
Labels: Reviewed by PO

#249 FIX_248_RESPONSIVE_AFFICHAGE_DATE_LISTE_EVENEMENTS
  templates/event/_event.html.twig
Labels: Reviewed by PO

#251 FIX_SERVICES_YAML
  config/services.yaml
Labels: Reviewed by PO

#252 Dev to Master
  config/services.yaml
Labels: Reviewed by PO
